version: "3.9"
services:
  server:
    build: ./server
    command: npm run server
    ports:
      - "9000:9000"
    environment:
      - SERVER_PORT=9000
    volumes:
      - ./server/:/app
      - /app/node_modules
  client:
    build: ./client
    command: npm run dev
    ports:
      - "8080:8080"
    environment:
      - VITE_PORT=8080
    volumes:
      - ./client/:/app
      - /app/node_modules
    